// <auto-generated />
using System;
using HandMotionPlay_.net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HandMotionPlay_.net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311050937_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HandMotionPlay_.net.Models.DailyPlatformStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveUsers")
                        .HasColumnType("integer");

                    b.Property<decimal>("AvgAccuracy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AvgSessionTime")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StatDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalScore")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUsers")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DailyPlatformStats");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.GameDailyStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgScore")
                        .HasColumnType("numeric");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StatDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalScore")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameDailyStats");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.GameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.GameStat", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AvgScore")
                        .HasColumnType("numeric");

                    b.Property<int>("TodaySessions")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPlayers")
                        .HasColumnType("integer");

                    b.Property<long>("TotalScore")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer");

                    b.HasKey("GameId");

                    b.ToTable("GameStats");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.PlatformStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PlatformStatuses");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.SessionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Accuracy")
                        .HasColumnType("numeric");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.UserStat", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvgAccuracy")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<long>("TotalScore")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer");

                    b.Property<long>("TotalTimeSeconds")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.GameDailyStat", b =>
                {
                    b.HasOne("HandMotionPlay_.net.Models.GameModel", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.GameStat", b =>
                {
                    b.HasOne("HandMotionPlay_.net.Models.GameModel", "Game")
                        .WithOne("GameStat")
                        .HasForeignKey("HandMotionPlay_.net.Models.GameStat", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.SessionModel", b =>
                {
                    b.HasOne("HandMotionPlay_.net.Models.GameModel", "Game")
                        .WithMany("Sessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HandMotionPlay_.net.Models.UserModel", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.UserStat", b =>
                {
                    b.HasOne("HandMotionPlay_.net.Models.UserModel", "User")
                        .WithOne("UserStat")
                        .HasForeignKey("HandMotionPlay_.net.Models.UserStat", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.GameModel", b =>
                {
                    b.Navigation("GameStat")
                        .IsRequired();

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("HandMotionPlay_.net.Models.UserModel", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("UserStat")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
